from robot.api.deco import keyword
import json

def generate_prompt_for_alternative_locators(page_source: str, locator_type: str, locator_value: str) -> str:
    prompt = f"""

        You are a Selenium and DOM analysis assistant.

        TASK:
        Your task is to analyze the provided HTML Page Source and generate alternative unique locators for the given element. As the 
        element's current locator is failing, you need to find other reliable ways to locate the same element by referring 
        supplied Locator Type and Locator Value, on the page. Focus on attributes and DOM structure that are less likely to change.
        Only return locators that can uniquely identify the element in the DOM in json format as specified below. If any locator 
        type is not applicable, return an empty string for that type. But do not share any explanations, notes, or text outside 
        the JSON object. The JSON should strictly follow the format provided.

        INPUT:

        HTML PAGE SOURCE:
        {page_source}

        Locator Type: {locator_type}
        Locator Value: {locator_value}

        OUTPUT RULES (STRICT):
        1. Return ONLY a valid JSON object.
        2. Do NOT include explanations.
        3. Do not include / add any solution examples or suggestions for locator generation.
        3. Do NOT include notes.
        4. Do NOT include markdown.
        5. Do NOT include text before or after JSON.

        INSTRUCTIONS:
        --------------
        1. Identify the exact element in the page source using the provided locator type and value, try to find similar elements.
        2. Analyze the element’s attributes and DOM structure.
        3. Generate alternative reliable and unique locators for the same element.
        4. Prioritize stable and automation-friendly attributes.
        5. Avoid dynamic attributes such as autogenerated IDs or dynamic class names (if detectable).
        6. Ensure each locator uniquely identifies the element within the DOM.

        JSON FORMAT (STRICT):
        {{
        "id": "",
        "name": "",
        "xpath": "",
        "cssSelector": "",
        "className": "",
        "linkText": ""
        }}

        Return valid JSON only."""

    return prompt

@keyword
def generate_prompt_for_alternative_self_healed_locators(page_source: str, locator_type: str, locator_value: str) -> str:
    """
    Robot Framework keyword to generate alternative locators JSON string.
    """
    return generate_prompt_for_alternative_locators(page_source, locator_type, locator_value)
